title: "Ashish Cyber Notes"
description: "Writeups, CTFs, and cybersecurity learning journey"
theme: minima

author:
  name: "Ashish"

markdown: kramdown

permalink: /:title/

collections:
  posts:
    output: true
